export default {
  GET_CURRENCIES_SUCCESS: 'GET_CURRENCIES_SUCCESS',
  SET_CONVERSION_STORAGE: 'SET_CONVERSION_STORAGE',
  SET_CONVERSION_STORAGE_FROM_SESSION_STORAGE: 'SET_CONVERSION_STORAGE_FROM_SESSION_STORAGE',
};
